---
##########################
## This role is preview ##
##########################

# - name: '[INIT:VARS] build network_list'
#   set_fact:
#   when: 'extend_network is not defined'
#     network_list: "{{ base_network }}"
# - set_fact:
#   when: 'extend_network is defined'
#     network_list: "{{ base_network + extend_network }}"



# - name: '[ACTION:Network] Change InterfaceName'
#   win_command: powershell.exe -
#   args:
#     stdin: Get-NetAdapter -InterfaceDescription "{{ item.names.adapter }}" | Select-Object Name
#   register: result
#   with_items:
#     - "{{ network_list }}"
# - win_command: powershell.exe -
#   when: item.names.nic_name in result
#   changed_when: 'item.names.nic_name not in result.stdout_lines'
#   args:
#     stdin: Get-NetAdapter -InterfaceDescription "{{ item.names.adapter }}" | Rename-NetAdapter -NewName "{{ item.names.nic_name }}"; Get-NetAdapter -InterfaceDescription "{{ item.names.adapter }}" | Select-Object Name
#   with_items:
#     - "{{ network_list }}"


# - name: '[ACTION:Network] Remove Default Gateway'
#   changed_when: '"0.0.0.0" not in result.stdout_lines'
#   win_command: powershell.exe -
#   args:
#     stdin: Remove-NetRoute -DestinationPrefix 0.0.0.0/0 -confirm:$false -ErrorAction SilentlyContinue; Get-NetRoute -AddressFamily IPv4 | Select-Object NextHop
#   register: result
#   ignore_errors: yes



# - name: "[PUSH:ResetInterface] Push files to destination"
#   win_template:
#     src: nicreset.j2
#     dest: C:\nicreset.ps1
#     output_encoding: SJIS 
#   with_items:
#     - "{{ win_nic }}"
# - name: '[ACTION:ResetInterface] Start IP config'
#   win_shell: C:\nicreset.ps1
#   async: 30
#   poll: 0
# - name: '[ACTION:ResetInterface] Fetch Connection'
#   wait_for_connection:
#     delay: 5
#     timeout: 600
# - name: '[CLEANUP:ResetInterface] Fetch Connection'
#   win_file:
#     path: '{{ item }}'
#     state: absent
#   with_items:
#     - C:\nicreset.ps1
#     - C:\nicreset.bat



- name: '[ACTION:Network-IPv6]Disable IPv6 components'
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisableComponents
    type: dword
    data: 0xff



