---
- when: 'extend_network is undefined'
  set_fact:
    network_list: '{{ base_network }}'
  delegate_to: localhost
- when: 'extend_network is defined'
  set_fact:
    network_list: "{{ base_network + extend_network }}"
  delegate_to: localhost

- name: '[INIT:FLUSH] Working Environment'
  file:
    path: '{{ item }}'
    state: "absent"
    force: yes
  with_items:
    - ./host_vars
    - ./group_vars
    - ./log
  delegate_to: localhost
  run_once: yes

- name: '[INIT:FACILITATE] Working Environment'
  file:
    path:  '{{ item }}'
    state: "directory"
    force: yes
  with_items:
    - ./host_vars
    - ./group_vars
    - ./log
  delegate_to: localhost
  run_once: yes

- name: '[ACTION:BUILD] Working host_vars'
  template:
    src:  host_vars.j2
    dest: ./host_vars/{{ inventory_hostname }}.yml
  delegate_to: localhost
